"""Dump the entire CircuitRubric corpus to a single Markdown file.

Includes every fixture's metadata, user prompts (all variants), reference
netlist(s), and ratio groups. Intended for review: formatted for read-through,
not for machine consumption.

Usage:
    python scripts/full_corpus.py [--output docs/full_corpus.md]
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURES_DIR = REPO_ROOT / "fixtures"
SYSTEM_PROMPTS_FILE = REPO_ROOT / "system_prompts.yaml"


def _read(path: Path) -> str:
    return path.read_text().rstrip()


def _render_system_prompts(out: list[str], sp_path: Path) -> None:
    if not sp_path.is_file():
        return
    doc = yaml.safe_load(sp_path.read_text()) or {}
    prompts = doc.get("prompts", [])
    if not prompts:
        return
    default_id = doc.get("default_id")
    out.append("## System Prompts")
    out.append("")
    out.append(
        "The scaffolding ladder used when prompting a model, from least to most "
        "prescriptive (source: `system_prompts.yaml`). The default level is "
        f"`{default_id}`." if default_id else
        "The scaffolding ladder used when prompting a model (source: `system_prompts.yaml`)."
    )
    out.append("")
    for entry in prompts:
        pid = entry.get("id", "?")
        tag = " _(default)_" if pid == default_id else ""
        out.append(f"### `{pid}`{tag}")
        out.append("")
        desc = (entry.get("description", "") or "").strip()
        if desc:
            out.append(desc)
            out.append("")
        # Prompt text as a soft-wrapped blockquote (a long single line in a code
        # fence overflows the page; a blockquote wraps in source and when rendered).
        text = (entry.get("text", "") or "").strip()
        for wrapped in textwrap.fill(text, width=92).split("\n"):
            out.append(f"> {wrapped}")
        out.append("")


def render_corpus(fixtures_dir: Path, sp_path: Path = SYSTEM_PROMPTS_FILE) -> str:
    out: list[str] = []
    out.append("# CircuitRubric Full Corpus")
    out.append("")
    out.append(
        "Auto-generated by `scripts/full_corpus.py`. Lists the system prompts, then "
        "every fixture (metadata, user prompts, reference netlist(s), ratio groups). "
        "Edit fixtures in `fixtures/<id>/` (and `system_prompts.yaml`), not this file."
    )
    out.append("")

    _render_system_prompts(out, sp_path)

    # ---- Fixtures ----
    out.append("## Fixtures")
    out.append("")

    fixture_dirs = sorted(
        d for d in fixtures_dir.iterdir()
        if d.is_dir() and d.name[:3].isdigit() and "_" in d.name
    )
    out.append(f"_Total: {len(fixture_dirs)} fixtures._")
    out.append("")

    for d in fixture_dirs:
        meta_path = d / "meta.yaml"
        prompts_path = d / "prompts.yaml"
        ratio_path = d / "ratio_groups.yaml"
        ref_paths = sorted(d.glob("reference*.cir"))

        if not meta_path.exists():
            out.append(f"### `{d.name}` — MISSING meta.yaml")
            out.append("")
            continue

        meta = yaml.safe_load(meta_path.read_text()) or {}
        prompts_doc = yaml.safe_load(prompts_path.read_text()) if prompts_path.exists() else {}
        ratio_doc = yaml.safe_load(ratio_path.read_text()) if ratio_path.exists() else {"groups": []}

        out.append(f"### `{d.name}`")
        out.append("")
        out.append(
            f"**Category/family/variant:** "
            f"{meta.get('category','?')}/{meta.get('family','?')}/{meta.get('variant','?')}"
        )
        out.append(f"**Source:** {meta.get('source','?')}")
        out.append("")

        # Prompts
        prompt_entries = (prompts_doc or {}).get("prompts", [])
        if prompt_entries:
            out.append("**Prompts:**")
            out.append("")
            for entry in prompt_entries:
                pid = entry.get("id", "?")
                ptext = (entry.get("text", "") or "").strip()
                out.append(f"- **{pid}** — {ptext}")
            out.append("")
        else:
            out.append("**Prompts:** (none defined)")
            out.append("")

        # References
        for ref in ref_paths:
            out.append(f"**`{ref.name}`:**")
            out.append("")
            out.append("```spice")
            out.append(_read(ref))
            out.append("```")
            out.append("")

        # Ratio groups
        groups = (ratio_doc or {}).get("groups", []) or []
        if groups:
            out.append("**Ratio groups:**")
            out.append("")
            for g in groups:
                devs = g.get("devices", [])
                rw = g.get("ratio_W")
                rl = g.get("ratio_L")
                rm = g.get("ratio_M")
                rv = g.get("ratio_value")
                parts = [f"devices={devs}"]
                if rw is not None: parts.append(f"W={rw}")
                if rl is not None: parts.append(f"L={rl}")
                if rm is not None: parts.append(f"M={rm}")
                if rv is not None: parts.append(f"value={rv}")
                out.append(f"- {', '.join(parts)}")
            out.append("")

        out.append("---")
        out.append("")

    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fixtures-dir", type=Path, default=FIXTURES_DIR,
        help="Root containing fixture directories.",
    )
    parser.add_argument(
        "--system-prompts", type=Path, default=SYSTEM_PROMPTS_FILE,
        help="System-prompts YAML to render (default: system_prompts.yaml; skipped if absent).",
    )
    parser.add_argument(
        "--output", type=Path, default=REPO_ROOT / "docs" / "full_corpus.md",
        help="Output Markdown file (default: docs/full_corpus.md).",
    )
    args = parser.parse_args()

    if not args.fixtures_dir.is_dir():
        print(f"ERROR: fixtures dir not found: {args.fixtures_dir}", file=sys.stderr)
        return 2

    text = render_corpus(args.fixtures_dir, args.system_prompts)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"Wrote {len(text):,} chars to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
